export const COUNTRIES = [
    // América Latina
    { name: 'Argentina', flag: '🇦🇷' },
    { name: 'México', flag: '🇲🇽' },
    { name: 'Chile', flag: '🇨🇱' },
    { name: 'Colombia', flag: '🇨🇴' },
    { name: 'Perú', flag: '🇵🇪' },
    { name: 'Uruguay', flag: '🇺🇾' },
    { name: 'Brasil', flag: '🇧🇷' },
    { name: 'Ecuador', flag: '🇪🇨' },
    { name: 'Bolivia', flag: '🇧🇴' },
    { name: 'Paraguay', flag: '🇵🇾' },
    { name: 'Venezuela', flag: '🇻🇪' },
    { name: 'Costa Rica', flag: '🇨🇷' },
    { name: 'Panamá', flag: '🇵🇦' },
    { name: 'Guatemala', flag: '🇬🇹' },
    { name: 'Honduras', flag: '🇭🇳' },
    { name: 'El Salvador', flag: '🇸🇻' },
    { name: 'Nicaragua', flag: '🇳🇮' },
    { name: 'República Dominicana', flag: '🇩🇴' },
    { name: 'Cuba', flag: '🇨🇺' },
    { name: 'Puerto Rico', flag: '🇵🇷' },

    // América del Norte
    { name: 'Estados Unidos', flag: '🇺🇸' },
    { name: 'Canadá', flag: '🇨🇦' },

    // Europa Occidental
    { name: 'España', flag: '🇪🇸' },
    { name: 'Francia', flag: '🇫🇷' },
    { name: 'Alemania', flag: '🇩🇪' },
    { name: 'Italia', flag: '🇮🇹' },
    { name: 'Portugal', flag: '🇵🇹' },
    { name: 'Reino Unido', flag: '🇬🇧' },
    { name: 'Países Bajos', flag: '🇳🇱' },
    { name: 'Bélgica', flag: '🇧🇪' },
    { name: 'Suiza', flag: '🇨🇭' },
    { name: 'Austria', flag: '🇦🇹' },
    { name: 'Irlanda', flag: '🇮🇪' },
    { name: 'Luxemburgo', flag: '🇱🇺' },

    // Europa del Norte
    { name: 'Suecia', flag: '🇸🇪' },
    { name: 'Noruega', flag: '🇳🇴' },
    { name: 'Dinamarca', flag: '🇩🇰' },
    { name: 'Finlandia', flag: '🇫🇮' },
    { name: 'Islandia', flag: '🇮🇸' },

    // Europa del Este
    { name: 'Polonia', flag: '🇵🇱' },
    { name: 'República Checa', flag: '🇨🇿' },
    { name: 'Hungría', flag: '🇭🇺' },
    { name: 'Rumania', flag: '🇷🇴' },
    { name: 'Bulgaria', flag: '🇧🇬' },
    { name: 'Croacia', flag: '🇭🇷' },
    { name: 'Eslovaquia', flag: '🇸🇰' },
    { name: 'Eslovenia', flag: '🇸🇮' },
    { name: 'Estonia', flag: '🇪🇪' },
    { name: 'Letonia', flag: '🇱🇻' },
    { name: 'Lituania', flag: '🇱🇹' },

    // Europa del Sur
    { name: 'Grecia', flag: '🇬🇷' },
    { name: 'Turquía', flag: '🇹🇷' },

    // Asia Oriental
    { name: 'Japón', flag: '🇯🇵' },
    { name: 'Corea del Sur', flag: '🇰🇷' },
    { name: 'China', flag: '🇨🇳' },
    { name: 'Taiwán', flag: '🇹🇼' },
    { name: 'Hong Kong', flag: '🇭🇰' },

    // Asia del Sur
    { name: 'India', flag: '🇮🇳' },
    { name: 'Pakistán', flag: '🇵🇰' },
    { name: 'Bangladesh', flag: '🇧🇩' },
    { name: 'Sri Lanka', flag: '🇱🇰' },

    // Sudeste Asiático
    { name: 'Singapur', flag: '🇸🇬' },
    { name: 'Tailandia', flag: '🇹🇭' },
    { name: 'Vietnam', flag: '🇻🇳' },
    { name: 'Filipinas', flag: '🇵🇭' },
    { name: 'Indonesia', flag: '🇮🇩' },
    { name: 'Malasia', flag: '🇲🇾' },

    // Medio Oriente
    { name: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
    { name: 'Arabia Saudita', flag: '🇸🇦' },
    { name: 'Israel', flag: '🇮🇱' },

    // Oceanía
    { name: 'Australia', flag: '🇦🇺' },
    { name: 'Nueva Zelanda', flag: '🇳🇿' },
    { name: 'Fiji', flag: '🇫🇯' },
    { name: 'Papua Nueva Guinea', flag: '🇵🇬' },

    // África
    { name: 'Sudáfrica', flag: '🇿🇦' },
    { name: 'Egipto', flag: '🇪🇬' },
    { name: 'Marruecos', flag: '🇲🇦' },
    { name: 'Kenia', flag: '🇰🇪' },
    { name: 'Nigeria', flag: '🇳🇬' },
];

export const NICHES = [
    { name: 'Videojuegos', emoji: '🎮' },
    { name: 'Gaming', emoji: '🕹️' },
    { name: 'Desarrollo de Software', emoji: '💻' },
    { name: 'Marketing Digital', emoji: '📱' },
    { name: 'Recursos Humanos', emoji: '👥' },
    { name: 'Salud y Bienestar', emoji: '🏥' },
    { name: 'E-learning / EdTech', emoji: '📚' },
    { name: 'FinTech', emoji: '💳' },
    { name: 'Logística', emoji: '📦' },
    { name: 'E-commerce', emoji: '🛒' },
    { name: 'Consultoría Estratégica', emoji: '💼' },
    { name: 'Ciberseguridad', emoji: '🔐' },
    { name: 'Inmobiliaria / Real Estate', emoji: '🏢' },
    { name: 'Turismo y Hospitalidad', emoji: '✈️' },
    { name: 'Banca y Seguros', emoji: '🏦' },
    { name: 'Agroindustria', emoji: '🌾' },
    { name: 'Energías Renovables', emoji: '⚡' },
    { name: 'Diseño Gráfico / Multimedia', emoji: '🎨' },
    { name: 'Legal / Abogacía', emoji: '⚖️' },
    { name: 'Arquitectura y Construcción', emoji: '🏗️' },
    { name: 'Telecomunicaciones', emoji: '📡' },
    { name: 'Medios y Entretenimiento', emoji: '🎬' },
    { name: 'Publicidad y Relaciones Públicas', emoji: '📢' },
    { name: 'Retail / Comercio Minorista', emoji: '🛍️' },
    { name: 'Manufactura', emoji: '🏭' },
    { name: 'Automotriz', emoji: '🚗' },
    { name: 'Aeroespacial', emoji: '🚀' },
    { name: 'Farmacéutica', emoji: '💊' },
    { name: 'Biotecnología', emoji: '🧬' },
    { name: 'Inteligencia Artificial', emoji: '🤖' },
    { name: 'Big Data / Analytics', emoji: '📊' },
    { name: 'Cloud Computing', emoji: '☁️' },
    { name: 'IoT (Internet de las Cosas)', emoji: '🌐' },
    { name: 'Blockchain / Criptomonedas', emoji: '₿' },
    { name: 'Robótica', emoji: '🦾' },
    { name: 'Realidad Virtual / Aumentada', emoji: '🥽' },
    { name: 'SaaS (Software as a Service)', emoji: '⚙️' },
    { name: 'Hardware / Electrónica', emoji: '🔌' },
    { name: 'Redes Sociales', emoji: '📲' },
    { name: 'Streaming / OTT', emoji: '📺' },
    { name: 'Podcasting', emoji: '🎙️' },
    { name: 'Influencer Marketing', emoji: '⭐' },
    { name: 'Alimentación y Bebidas', emoji: '🍽️' },
    { name: 'Gastronomía', emoji: '👨‍🍳' },
    { name: 'Moda y Textil', emoji: '👗' },
    { name: 'Cosmética y Belleza', emoji: '💄' },
    { name: 'Deportes y Fitness', emoji: '⚽' },
    { name: 'Educación', emoji: '🎓' },
    { name: 'Investigación Científica', emoji: '🔬' },
    { name: 'ONGs / Organizaciones sin fines de lucro', emoji: '🤝' },
    { name: 'Gobierno y Sector Público', emoji: '🏛️' },
    { name: 'Medioambiente y Sostenibilidad', emoji: '🌱' },
    { name: 'Reciclaje', emoji: '♻️' },
    { name: 'Agricultura / Agtech', emoji: '🚜' },
    { name: 'Pesca y Acuicultura', emoji: '🐟' },
    { name: 'Minería', emoji: '⛏️' },
    { name: 'Petróleo y Gas', emoji: '🛢️' },
    { name: 'Servicios Profesionales', emoji: '🎯' },
    { name: 'Contabilidad', emoji: '🧮' },
    { name: 'Auditoría', emoji: '📋' },
    { name: 'Traducción e Interpretación', emoji: '🌍' },
    { name: 'Eventos y Conferencias', emoji: '🎪' },
    { name: 'Catering', emoji: '🍴' },
    { name: 'Fotografía y Videografía', emoji: '📷' },
    { name: 'Música', emoji: '🎵' },
    { name: 'Artes Plásticas', emoji: '🖼️' },
    { name: 'Editorial / Publicaciones', emoji: '📖' },
    { name: 'Bibliotecas y Archivos', emoji: '📚' },
    { name: 'Mobiliario y Decoración', emoji: '🛋️' },
    { name: 'Jardines y Paisajismo', emoji: '🌳' },
    { name: 'Seguridad Privada', emoji: '🔒' },
    { name: 'Limpieza y Mantenimiento', emoji: '🧹' },
    { name: 'Transporte y Movilidad', emoji: '🚌' },
    { name: 'Aviación', emoji: '✈️' },
    { name: 'Marítimo / Naviero', emoji: '⚓' },
    { name: 'Ferroviario', emoji: '🚂' },
    { name: 'Courier / Mensajería', emoji: '📮' },
    { name: 'Almacenamiento / Warehousing', emoji: '🏬' },
];
